
services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-bullyguard}"
    image: bullyguard-data
    container_name: bullyguard-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-bar3126}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #  - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME}/.ssh
    ports:
      - 8888:8888
    ipc: host
    init: true

      